tic_tac_toe_client:
    resource: "@TicTacToeClientBundle/Resources/config/routing.yml"
    prefix:   /

tic_tac_toe_api:
    resource: "@TicTacToeApiBundle/Resources/config/routing.yml"
    prefix:   /api/v1/


